const products = [
  {
    id: 1,
    name: 'Organic Almonds',
    category: 'Snacks',
    price: 15.99,
    currency: 'USD',
    description: 'Raw, unsalted, organic almonds packed with nutrients.',
    images: ['https://i.ibb.co.com/h8t6V2j/Group-1-2.jpg', 'https://i.ibb.co.com/LvwTBDF/Group-1-3.jpg'],
    rating: 4.8,
    reviews: 102,
    stock: 150,
    brand: "Nature's Finest",
    certifications: ['USDA Organic', 'Non-GMO'],
    weight: '16 oz',
    dimensions: {
      length: 6,
      width: 4,
      height: 2,
    },
    ingredients: ['Organic Almonds'],
    tags: ['nuts', 'snacks', 'healthy'],
  },
  {
    id: 2,
    name: 'Organic Green Tea',
    category: 'Beverages',
    price: 9.99,
    currency: 'USD',
    description: 'Refreshing organic green tea sourced from sustainable farms.',
    images: ['https://i.ibb.co.com/9W4XfKj/Group-1-4.jpg', 'https://i.ibb.co.com/sF6fmZ4/Group-1-5.jpg'],
    rating: 4.6,
    reviews: 89,
    stock: 200,
    brand: 'PureLeaf Organics',
    certifications: ['USDA Organic', 'Fair Trade'],
    weight: '20 tea bags',
    dimensions: {
      length: 5,
      width: 3,
      height: 3,
    },
    ingredients: ['Organic Green Tea'],
    tags: ['tea', 'beverage', 'caffeine'],
  },
  {
    id: 3,
    name: 'Virgin Coconut Oil',
    category: 'Cooking',
    price: 12.49,
    currency: 'USD',
    description: 'Cold-pressed, virgin organic coconut oil perfect for cooking and skincare.',
    images: ['https://i.ibb.co.com/jMpX49k/Group-1-6.jpg', 'https://i.ibb.co.com/BNw3mqX/Group-1-7.jpg'],
    rating: 4.9,
    reviews: 150,
    stock: 120,
    brand: 'Tropical Naturals',
    certifications: ['USDA Organic', 'Non-GMO'],
    weight: '16 oz',
    dimensions: {
      length: 4,
      width: 4,
      height: 6,
    },
    ingredients: ['Organic Coconut Oil'],
    tags: ['cooking', 'oil', 'skincare'],
  },
  {
    id: 4,
    name: 'Organic Cabbage (BadhaKopi)',
    category: 'Vegetable',
    price: 12.49,
    currency: 'USD',
    description: 'Cold-pressed, virgin organic coconut oil perfect for cooking and skincare.',
    images: ['https://i.ibb.co.com/DCmYVpn/Group-1-1.jpg', 'https://i.ibb.co.com/DCmYVpn/Group-1-1.jpg'],
    rating: 4.9,
    reviews: 150,
    stock: 120,
    brand: 'Tropical Naturals',
    certifications: ['USDA Organic', 'Non-GMO'],
    weight: '16 oz',
    dimensions: {
      length: 4,
      width: 4,
      height: 6,
    },
    ingredients: ['Organic Coconut Oil'],
    tags: ['cooking', 'oil', 'skincare'],
  },
  {
    id: 5,
    name: 'Organic Apple',
    category: 'Fruits',
    price: 12.49,
    currency: 'USD',
    description: 'Cold-pressed, virgin organic coconut oil perfect for cooking and skincare.',
    images: ['https://i.ibb.co.com/5RtykCZ/Group-1-8.jpg', 'https://i.ibb.co.com/5RtykCZ/Group-1-8.jpg'],
    rating: 4.9,
    reviews: 150,
    stock: 120,
    brand: 'Tropical Naturals',
    certifications: ['USDA Organic', 'Non-GMO'],
    weight: '16 oz',
    dimensions: {
      length: 4,
      width: 4,
      height: 6,
    },
    ingredients: ['Organic Coconut Oil'],
    tags: ['cooking', 'oil', 'skincare'],
  },
  {
    id: 6,
    name: 'Organic Banana',
    category: 'Fruits',
    price: 15.99,
    currency: 'USD',
    description: 'Raw, unsalted, organic almonds packed with nutrients.',
    images: ['https://i.ibb.co.com/VT5g9N7/Group-1-9.jpg', 'https://i.ibb.co.com/VT5g9N7/Group-1-9.jpg'],
    rating: 4.8,
    reviews: 102,
    stock: 150,
    brand: "Nature's Finest",
    certifications: ['USDA Organic', 'Non-GMO'],
    weight: '16 oz',
    dimensions: {
      length: 6,
      width: 4,
      height: 2,
    },
    ingredients: ['Organic Almonds'],
    tags: ['nuts', 'snacks', 'healthy'],
  },
  {
    id: 7,
    name: 'Organic Carrot',
    category: 'Vegetables',
    price: 9.99,
    currency: 'USD',
    description: 'Refreshing organic green tea sourced from sustainable farms.',
    images: ['https://i.ibb.co.com/wQkB6bZ/Group-1-11.jpg', 'https://i.ibb.co.com/wQkB6bZ/Group-1-11.jpg'],
    rating: 4.6,
    reviews: 89,
    stock: 200,
    brand: 'PureLeaf Organics',
    certifications: ['USDA Organic', 'Fair Trade'],
    weight: '20 tea bags',
    dimensions: {
      length: 5,
      width: 3,
      height: 3,
    },
    ingredients: ['Organic Green Tea'],
    tags: ['tea', 'beverage', 'caffeine'],
  },
  {
    id: 8,
    name: 'Organic Mango',
    category: 'Fruits',
    price: 12.49,
    currency: 'USD',
    description: 'Cold-pressed, virgin organic coconut oil perfect for cooking and skincare.',
    images: ['https://i.ibb.co.com/029mfnP/Group-1-10.jpg', 'https://i.ibb.co.com/029mfnP/Group-1-10.jpg'],
    rating: 4.9,
    reviews: 150,
    stock: 120,
    brand: 'Tropical Naturals',
    certifications: ['USDA Organic', 'Non-GMO'],
    weight: '16 oz',
    dimensions: {
      length: 4,
      width: 4,
      height: 6,
    },
    ingredients: ['Organic Coconut Oil'],
    tags: ['cooking', 'oil', 'skincare'],
  },
  {
    id: 9,
    name: 'Organic Peanut',
    category: 'Vegetable',
    price: 12.49,
    currency: 'USD',
    description: 'Cold-pressed, virgin organic coconut oil perfect for cooking and skincare.',
    images: ['https://i.ibb.co.com/y65138H/Group-1-13.jpg', 'https://i.ibb.co.com/y65138H/Group-1-13.jpg'],
    rating: 4.9,
    reviews: 150,
    stock: 120,
    brand: 'Tropical Naturals',
    certifications: ['USDA Organic', 'Non-GMO'],
    weight: '16 oz',
    dimensions: {
      length: 4,
      width: 4,
      height: 6,
    },
    ingredients: ['Organic Coconut Oil'],
    tags: ['cooking', 'oil', 'skincare'],
  },
  {
    id: 10,
    name: 'Organic Eggplant(Bengun)',
    category: 'Vegetable',
    price: 12.49,
    currency: 'USD',
    description: 'Cold-pressed, virgin organic coconut oil perfect for cooking and skincare.',
    images: ['https://i.ibb.co.com/vjW524K/Group-1-12.jpg', 'https://i.ibb.co.com/vjW524K/Group-1-12.jpg'],
    rating: 4.9,
    reviews: 150,
    stock: 120,
    brand: 'Tropical Naturals',
    certifications: ['USDA Organic', 'Non-GMO'],
    weight: '16 oz',
    dimensions: {
      length: 4,
      width: 4,
      height: 6,
    },
    ingredients: ['Organic Coconut Oil'],
    tags: ['cooking', 'oil', 'skincare'],
  },
];

export default products;
