import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Navbar from '@/shared/navbar/Navbar';
import MegaMenu from '@/shared/navbar/Megamenu';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1280px] m-auto px-1 lg:px-0 `}>
        <Navbar />
        <div className='z-50'>
          <MegaMenu />
        </div>

        <div className='z-40'>{children}</div>
      </body>
    </html>
  );
}
