const outlets = [
  {
    storeId: '001',
    storeName: 'Green Avenue Outlet',
    location: {
      address: '123 Green Avenue',
      city: 'Dhaka',
      state: 'Dhaka',
      zipCode: '1000',
    },
    contact: {
      phone: '+880 123-456-7890',
      email: 'contact@organic.hookeyfresh.com',
    },
    categories: ['Fruits', 'Vegetables', 'Dairy', 'Bakery', 'Pantry'],
    openingHours: {
      saturday: '9:00 AM - 7:00 PM',
      sunday: '9:00 AM - 7:00 PM',
      monday: '9:00 AM - 7:00 PM',
      tuesday: '9:00 AM - 7:00 PM',
      wednesday: '9:00 AM - 7:00 PM',
      thursday: '9:00 AM - 7:00 PM',
      friday: '10:00 AM - 5:00 PM',
    },
  },
  {
    storeId: '002',
    storeName: 'Shyamoli Outlet',
    location: {
      address: 'Saraho Plaza, 8/KA, PC Culture Housing Society, Ring Road',
      city: 'Dhaka',
      state: 'Dhaka',
      zipCode: '1000',
    },
    contact: {
      phone: '+880 123-456-7890',
      email: 'contact@organic.hookeyfresh.com',
    },
    categories: ['Fruits', 'Vegetables', 'Dairy', 'Bakery', 'Pantry'],
    openingHours: {
      saturday: '9:00 AM - 7:00 PM',
      sunday: '9:00 AM - 7:00 PM',
      monday: '9:00 AM - 7:00 PM',
      tuesday: '9:00 AM - 7:00 PM',
      wednesday: '9:00 AM - 7:00 PM',
      thursday: '9:00 AM - 7:00 PM',
      friday: '10:00 AM - 5:00 PM',
    },
  },
  {
    storeId: '003',
    storeName: 'Mirpur 10 Outlet',
    location: {
      address: 'Shatabdi Bhabon, Plot – 19, Road No- 1, Senpara Parbata',
      city: 'Dhaka',
      state: 'Dhaka',
      zipCode: '1000',
    },
    contact: {
      phone: '+880 123-456-7890',
      email: 'contact@organic.hookeyfresh.com',
    },
    categories: ['Fruits', 'Vegetables', 'Dairy', 'Bakery', 'Pantry'],
    openingHours: {
      saturday: '9:00 AM - 7:00 PM',
      sunday: '9:00 AM - 7:00 PM',
      monday: '9:00 AM - 7:00 PM',
      tuesday: '9:00 AM - 7:00 PM',
      wednesday: '9:00 AM - 7:00 PM',
      thursday: '9:00 AM - 7:00 PM',
      friday: '10:00 AM - 5:00 PM',
    },
  },
  {
    storeId: '004',
    storeName: 'Banasree Outlet',
    location: {
      address: 'House- 43, Road- 4, Block- E, Banasree',
      city: 'Dhaka',
      state: 'Dhaka',
      zipCode: '1000',
    },
    contact: {
      phone: '+880 123-456-7890',
      email: 'contact@organic.hookeyfresh.com',
    },
    categories: ['Fruits', 'Vegetables', 'Dairy', 'Bakery', 'Pantry'],
    openingHours: {
      saturday: '9:00 AM - 7:00 PM',
      sunday: '9:00 AM - 7:00 PM',
      monday: '9:00 AM - 7:00 PM',
      tuesday: '9:00 AM - 7:00 PM',
      wednesday: '9:00 AM - 7:00 PM',
      thursday: '9:00 AM - 7:00 PM',
      friday: '10:00 AM - 5:00 PM',
    },
  },
  {
    storeId: '005',
    storeName: 'Khulshi Outlet',
    location: {
      address: '9R63+M6Q, Zakir Hossain Road, Khulsi',
      city: 'Chittagong',
      state: 'Chittagong',
      zipCode: '1000',
    },
    contact: {
      phone: '+880 123-456-7890',
      email: 'contact@organic.hookeyfresh.com',
    },
    categories: ['Fruits', 'Vegetables', 'Dairy', 'Bakery', 'Pantry'],
    openingHours: {
      saturday: '9:00 AM - 7:00 PM',
      sunday: '9:00 AM - 7:00 PM',
      monday: '9:00 AM - 7:00 PM',
      tuesday: '9:00 AM - 7:00 PM',
      wednesday: '9:00 AM - 7:00 PM',
      thursday: '9:00 AM - 7:00 PM',
      friday: '10:00 AM - 5:00 PM',
    },
  },
  {
    storeId: '006',
    storeName: 'Agrabaad Outlet',
    location: {
      address: '9R63+M6Q, Zakir Hossain Road, Agrabaad',
      city: 'Chittagong',
      state: 'Chittagong',
      zipCode: '1000',
    },
    contact: {
      phone: '+880 123-456-7890',
      email: 'contact@organic.hookeyfresh.com',
    },
    categories: ['Fruits', 'Vegetables', 'Dairy', 'Bakery', 'Pantry'],
    openingHours: {
      saturday: '9:00 AM - 7:00 PM',
      sunday: '9:00 AM - 7:00 PM',
      monday: '9:00 AM - 7:00 PM',
      tuesday: '9:00 AM - 7:00 PM',
      wednesday: '9:00 AM - 7:00 PM',
      thursday: '9:00 AM - 7:00 PM',
      friday: '10:00 AM - 5:00 PM',
    },
  },
];

export default outlets;
